
seed: 42

dataset: 'MNIST-CIFAR'

dataset_params:
  ID:
    causal_noise: 0.0
    spurious_ratio: 0.10
  OOD:
    causal_noise: 0.0
    spurious_ratio: 0.5
  val_ratio: 0.2
  batch_size: 80
  data_path: "/home/armand/repos/diverse-vit/cached/"

target_name: 'target'

model: 'DiverseViT'
model_params:
  image_size: [64, 32]
  patch_size: 4
  num_classes: 2
  channels: 3
  dim: 64
  depth: 6
  heads: 4
  mlp_dim: 128


optimizer: 'adam'
optimizer_params:
  lr: 0.0001

diversification:
  weight: 0.0
  normalization: "per_token"


scheduler: 'MultiStepLR'
scheduler_params:
  milestones: [70, 80]
  gamma: 0.1

num_epochs: 100

logging_path: "/home/armand/repos/diverse-vit/results_logs/"
checkpoints_path: "/home/armand/repos/diverse-vit/checkpoints/"

checkpoint: null
